#!/usr/bin/env node
// scripts/compile-nodes.mjs
// Compile raw/nodes/*.md + scripts/legacy-*.js → docs/data.js + docs/nodes.json

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

import { parseFrontmatter } from './compile-nodes/frontmatter.mjs';
import { renderSection, splitLanguageSections } from './compile-nodes/markdown.mjs';
import { validateNode } from './compile-nodes/schema.mjs';
import { mergeNodes, normalizeEdges, validateEdges } from './compile-nodes/merge.mjs';

async function loadDataCategories(projectRoot) {
  const src = await readFile(join(projectRoot, 'docs', 'data.js'), 'utf8');
  const ctx = vm.createContext({ window: {} });
  vm.runInContext(src, ctx, { filename: 'docs/data.js' });
  if (!ctx.window.VIBEMAP_DATA) throw new Error('docs/data.js must set window.VIBEMAP_DATA');
  return ctx.window.VIBEMAP_DATA.categories;
}

async function loadLegacyFile(path, globalKey) {
  const src = await readFile(path, 'utf8');
  const ctx = vm.createContext({ module: { exports: null }, globalThis: {} });
  vm.runInContext(src, ctx, { filename: path });
  return ctx.module.exports || ctx.globalThis[globalKey] || [];
}

async function loadLegacy(projectRoot) {
  const nodes = await loadLegacyFile(join(projectRoot, 'scripts', 'legacy-nodes.js'), 'LEGACY_NODES');
  const edges = await loadLegacyFile(join(projectRoot, 'scripts', 'legacy-edges.js'), 'LEGACY_EDGES');
  return { nodes, edges };
}

async function loadMarkdownNodes(projectRoot, knownCats) {
  const dir = join(projectRoot, 'raw', 'nodes');
  let files;
  try { files = await readdir(dir); } catch { return []; }
  const md = [];
  for (const file of files.sort()) {
    if (!file.endsWith('.md')) continue;
    const path = join(dir, file);
    const src = await readFile(path, 'utf8');
    const { data, body } = parseFrontmatter(src);
    validateNode(data, { knownCats, file });
    const sections = splitLanguageSections(body);
    const bodyHtml = {};
    const wikiLinks = new Set();
    for (const lang of ['ko', 'en', 'ja']) {
      const { html, wikiLinks: links } = renderSection(sections[lang]);
      bodyHtml[lang] = html;
      for (const l of links) wikiLinks.add(l);
    }
    md.push({
      ...data,
      _bodyHtml: bodyHtml,
      _wikiLinks: [...wikiLinks],
    });
  }
  return md;
}

function buildEdges({ mdNodes, legacyEdges, byId }) {
  const all = [];
  for (const n of mdNodes) {
    for (const target of n._wikiLinks) all.push([n.id, target]);
    for (const target of (n.extraEdges || [])) all.push([n.id, target]);
  }
  for (const e of legacyEdges) all.push([e[0], e[1]]);
  const normalized = normalizeEdges(all);
  return validateEdges(normalized, byId);
}

function serializeDataJs(categories, nodes, edges) {
  const catKeys = Object.keys(categories);
  const catOrder = Object.fromEntries(catKeys.map((k, i) => [k, i]));
  const nodeLines = [...nodes].sort((a, b) => {
    const ca = catOrder[a.cat] ?? 999;
    const cb = catOrder[b.cat] ?? 999;
    if (ca !== cb) return ca - cb;
    return a.id.localeCompare(b.id);
  }).map((n) => {
    const title = JSON.stringify(n.title);
    return `  { id: ${JSON.stringify(n.id)}, cat: ${JSON.stringify(n.cat)}, size: ${n.size}, title: ${title} }`;
  }).join(',\n');
  const catLiteral = catKeys.map((k) => {
    const c = categories[k];
    return `    ${k}: { color: ${JSON.stringify(c.color)}, label: ${JSON.stringify(c.label)} }`;
  }).join(',\n');
  const edgeLines = edges.map(([a, b]) => `  [${JSON.stringify(a)}, ${JSON.stringify(b)}]`).join(',\n');
  return `// AUTO-GENERATED by scripts/compile-nodes.mjs — do not edit by hand.\n` +
    `// Source: raw/nodes/*.md + scripts/legacy-*.js\n` +
    `window.VIBEMAP_DATA = {\n` +
    `  categories: {\n${catLiteral}\n  },\n` +
    `  nodes: [\n${nodeLines}\n  ],\n` +
    `  edges: [\n${edgeLines}\n  ]\n` +
    `};\n`;
}

function serializeNodesJson(byId, generatedAt) {
  const nodes = {};
  const sortedIds = Object.keys(byId).sort();
  for (const id of sortedIds) {
    const n = byId[id];
    if (n._source === 'md') {
      nodes[id] = { body: n._bodyHtml, refs: n.refs || [] };
    } else {
      const body = {};
      for (const lang of ['ko', 'en', 'ja']) {
        const raw = (n.body && n.body[lang]) || '';
        body[lang] = raw ? `<p>${escapeHtml(raw).replace(/\n/g, '<br>')}</p>` : '';
      }
      nodes[id] = { body, refs: [] };
    }
  }
  const stats = {
    total: sortedIds.length,
    fromMarkdown: Object.values(byId).filter((n) => n._source === 'md').length,
    fromLegacy: Object.values(byId).filter((n) => n._source === 'legacy').length,
  };
  return JSON.stringify({
    version: '1',
    generatedAt,
    source: 'raw/nodes/ + scripts/legacy-*.js',
    stats,
    nodes,
  }, null, 2) + '\n';
}

function escapeHtml(s) {
  return String(s).replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
}

export async function compile({ projectRoot, strict = false, now }) {
  const categories = await loadDataCategories(projectRoot);
  const knownCats = new Set(Object.keys(categories));
  const legacy = await loadLegacy(projectRoot);
  const md = await loadMarkdownNodes(projectRoot, knownCats);
  const { byId, stats } = mergeNodes({ legacy: legacy.nodes, md });
  const { valid: validEdges, broken } = buildEdges({ mdNodes: md, legacyEdges: legacy.edges, byId });

  if (broken.length > 0) {
    const msg = `⚠ ${broken.length} broken edge(s): ${broken.map(e => `[${e[0]}→${e[1]}]`).join(', ')}`;
    console.warn(msg);
    if (strict) throw new Error(msg);
  }

  const nodesArr = Object.values(byId);
  const dataJs = serializeDataJs(categories, nodesArr, validEdges);
  const nodesJson = serializeNodesJson(byId, now ?? new Date().toISOString());
  await writeFile(join(projectRoot, 'docs', 'data.js'), dataJs, 'utf8');
  await writeFile(join(projectRoot, 'docs', 'nodes.json'), nodesJson, 'utf8');

  return {
    stats: { ...stats, total: nodesArr.length, edges: validEdges.length, brokenEdges: broken.length },
    edges: validEdges,
    dataJsBytes: Buffer.byteLength(dataJs),
    nodesJsonBytes: Buffer.byteLength(nodesJson),
  };
}

async function main() {
  const strict = process.argv.includes('--strict');
  const here = dirname(fileURLToPath(import.meta.url));
  const projectRoot = join(here, '..');
  const result = await compile({ projectRoot, strict });
  const { stats } = result;
  console.log(`docs/data.js + docs/nodes.json written: ${stats.total} node(s) (${stats.fromMarkdown} md, ${stats.fromLegacy} legacy), ${stats.edges} edges, ${stats.brokenEdges} broken.`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => { console.error(err.stack || err.message); process.exit(1); });
}
